<template>
  <div>
    <h1>The Dreaming Sat</h1>

    <div>
      <h3>Current Coordinates:</h3>
      <p>{{ coordinates_sat }}</p>
    </div>

    <div class="section">
      <h3>Gemini Response (Location):</h3>
      <div>{{ gemini_response }}</div>
    </div>

    <div class="section">
      <h3>Satellite Image (Generated by Gemini):</h3>
      <img v-if="geminiImageUrl" :src="geminiImageUrl" alt="Gemini Generated Satellite View" />
      <p v-else>Loading Gemini-generated image...</p>
    </div>
  </div>
</template>

<script>
import { GoogleGenerativeAI } from "@google/generative-ai";

const API_KEY = process.env.VUE_APP_API;
const genAI = new GoogleGenerativeAI("AIzaSyCZjHuMPr9JPA37ps8Gs1z3xgN9x3LGVB0");

export default {
  name: 'App',
  data() {
    return {
      sat_data: null,
      interval: null,
      coordinates_sat: '',
      gemini_response: '',
      geminiImageUrl: '',
      prompt: '',
    };
  },

  mounted() {
    this.fetch_data();
    this.interval = setInterval(() => {
      this.coordinates_sat = this.sat_data.features.map(d => d.geometry.coordinates);
      this.fetch_data();
    }, 30000);
  },

  watch: {
    coordinates_sat: {
      deep: true,
      handler(newCoords) {
        if (newCoords[0][1] && newCoords[1][1] && newCoords[2][1]) {
          this.prompt = `What is the place located at latitude ${newCoords[0][1]}, longitude ${newCoords[1][1]} and altitude ${newCoords[2][1]}? Provide only the name.`;
          this.sendToGemini();

          // Also generate satellite image from Gemini
          this.generateGeminiImage(newCoords[0][1], newCoords[1][1]);
        }
      },
    },
  },

  methods: {
    async fetch_data() {
      try {
        const res = await fetch(`https://api.spectator.earth/satellite/?api_key=${API_KEY}`, { cache: "no-store" });
        if (!res.ok) throw new Error(`API Error: ${res.status}`);
        this.sat_data = await res.json();
      } catch (error) {
        console.error("Fetch error:", error);
      }
    },

    async sendToGemini() {
      try {
        const model = genAI.getGenerativeModel({ model: "gemini-2.0-flash" });
        const result = await model.generateContent(this.prompt);
        this.gemini_response = result.response.text();
      } catch (error) {
        console.error("Gemini text generation error:", error);
      }
    },

    async generateGeminiImage(lat, lon) {
      const imagePrompt = `Generate a realistic, high-quality satellite-style aerial view of latitude ${lat} and longitude ${lon}, clearly showing terrain, vegetation, rivers, roads, and buildings.`;

      const model = genAI.getGenerativeModel({
        model: "gemini-2.0-flash-exp-image-generation",
        generationConfig: {
          responseModalities: ['Text', 'Image']
        },
      });

      try {
        const result = await model.generateContent(imagePrompt);
        
        let imageGenerated = false;

        for (const part of result.response.candidates[0].content.parts) {
          if (part.inlineData) {
            this.geminiImageUrl = `data:image/png;base64,${part.inlineData.data}`;
            imageGenerated = true;
            break;
          }
        }

        if (!imageGenerated) {
          console.error("Gemini didn't return valid inline image data.");
          this.geminiImageUrl = '';
        }

      } catch (error) {
        console.error("Gemini image generation error:", error);
        this.geminiImageUrl = '';
      }
    },
  },

  beforeUnmount() {
    clearInterval(this.interval);
  },
};
</script>

<style scoped>
.section {
  margin-top: 20px;
}

img {
  max-width: 100%;
  border-radius: 8px;
  border: 1px solid #ddd;
}
</style>
